services:
  web:
    build: .
    container_name: coldchain-web
    env_file: .env
    command: ["/entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app:delegated

  worker:
      build: .
      container_name: coldchain-worker
      env_file: .env
      command: ["python","-u","manage.py","mqtt_worker"]  # <- add -u
      depends_on:
        - db
        - mosquitto
      volumes:
      - ./app:/app:delegated


  mosquitto:
    image: eclipse-mosquitto:2
    container_name: coldchain-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/conf:/mosquitto/config:ro

  db:
    image: postgres:16-alpine
    container_name: coldchain-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-coldchain}
      POSTGRES_USER: ${POSTGRES_USER:-coldchain}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-coldchain}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  telegram-bot:
    build: .
    command: ["python","-u","manage.py","telegram_bot"]  # -u = unbuffered logs
    env_file: .env
    depends_on:
      - web
    volumes:
      - ./app:/app:delegated
    restart: unless-stopped
  

volumes:
  pgdata:
